### ISSUE TITLE
Add --class option

### ISSUE THREAD

**Issue by BaronBodissey** [macro187/testrunner#22]
To run only particular test class(es).

Original request:

Could you add some arguments to the command line to limit the run to any/some testclass or any/some testmethod

ex:

  testrunner.exe C:\Path\To\TestAssembly.dll C:\Path\To\AnotherTestAssembly.dll -c "xxxns.yyyyns.MyTestClass1,xxxns.zzzns.MyTestClass2" -m "xxxns.zzzns.MyTestClass3.TestingMethod1,......"

**Comment by macro187** [comment]
Split out a separate issue #24 for a --method option.

**Comment by macro187** [comment]
Added --class option and released as part of version 1.9.0
