### ISSUE TITLE
TestContext support

### ISSUE THREAD

**Issue by eczimmermann** [macro187/testrunner#7]
Hi,

I don't have the TestContext available in my Tests (e.g. in a [AssemblyInitialize] method) if I run the test with the testrunner.exe. 

Is it possible to get the TestContext in another way or do you know how to fix the problem?

Many thanks!

**Comment by macro187** [comment]
Hi eczimmermann,

You're right:  TestRunner doesn't support TestContext at this time.  What part of it do you require?

Regards,
Ron

**Comment by eczimmermann** [comment]
Hi macro187,

thank you for your answer.
Ok. Will you implement it in the near future? 

At the moment I need "AddResultFile" and "TestResultDirectory" of TestContext. But eventually I'll need more.

**Comment by macro187** [comment]
Hi eczimmermann,

I think this can be done.

I work on TestRunner in my spare time, so can't tell you when I might be able to do it.

Regards,
Ron

**Comment by macro187** [comment]
TestContext documentation <https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.testtools.unittesting.testcontext.aspx>

**Comment by gildorwang** [comment]
We also need `TestContext`. Specifically we need `TestName`, `FullyQualifiedTestClassName` and `CurrentTestOutcome`. Will they be supported?

**Comment by macro187** [comment]
Hi @gildorwang,

Those will be supported if I (or someone else) gets around to implementing them.  There is some tricky reflection / runtime code generation required that I don't quite know how to do yet.  I am maintaining notes in this GitHub issue as I work towards it.

Regards,
Ron

**Comment by macro187** [comment]
An initial cut of the dynamically-created `TestContext` is complete.  Next will be adding implementations for the individual members.

**Comment by macro187** [comment]
TestContext `.TestName` and `.FullyQualifiedTestClassName` implemented

**Comment by macro187** [comment]
`TestContext.CurrentTestOutcome` implemented

**Comment by macro187** [comment]
Moving `TestRunDirectory` and related functionality to separate issue #15 because it's a larger piece of work
